name: basic workflow

on: push
  # pull_request:
  #   branches:
  #     - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - name: activate the environment and run tests
        run: |
          cd $WORKING_DIR
          chmod +x ./scripts/venv.sh
          chmod +x ./scripts/run_tests.sh
          chmod +x ./app/test_main.py
          chmod +x ./scripts/summarize_results.sh
          source ./scripts/venv.sh
          ./scripts/run_tests.sh
        continue-on-error: true

      - name: summarize results
        run: |
          ./scripts/summarize_results.sh > ./test_summary.txt
          cat ./test_summary.txt
      
      - name: Upload Test Summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: ./test_summary.txt
      
      
