name: basic workflow

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - name: activate the environment
        run: |
          chmod +x $WORKING_DIR/scripts/venv.sh
          chmod +x $WORKING_DIR/scripts/run_tests.sh
          chmod +x $WORKING_DIR/app/test_main.py
          source $WORKING_DIR/scripts/venv.sh
          bash $WORKING_DIR/scripts/run_tests.sh
          